# Generated by Django 3.1.7 on 2021-08-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incrementidbdl',
            name='name_doc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incrementidbdl',
            name='nik',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
