# Generated by Django 3.1.7 on 2021-08-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210807_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLogbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(blank=True, max_length=20, null=True)),
                ('nik', models.CharField(blank=True, max_length=6, null=True)),
                ('docreceipt', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
